### ISSUE TITLE
浮动窗口只支持视频吗

### ISSUE THREAD

**Issue by wanghongenpin** [student9128/flutter_float_window#2]
能否支持自定义内容，安卓好像可以，ios不知道可以不，我看百度地图回到主页面也有浮动窗口

**Comment by student9128** [comment]
> 

自定义内容指的什么？

**Comment by wanghongenpin** [comment]
右下角小窗口不是视频，自定义的内容，我了解到安卓可以达到这个效果，不知道ios可以不
![image](https://github.com/student9128/flutter_float_window/assets/24794200/9f20e7f9-86b2-460c-a7a6-4da5eb9fc622)

**Comment by student9128** [comment]
应用内的可以自己写一个，应用外的话，用ios的画中画，也可以自己在上面添加一些内容

**Comment by wanghongenpin** [comment]
> 应用内的可以自己写一个，应用外的话，用ios的画中画，也可以自己在上面添加一些内容

大佬，你这个插件可以支持吗

**Comment by student9128** [comment]
这个不行🤣，这个只做了视频和直播，网上有相关的可以参考
