### ISSUE TITLE
Can play .avi video in iOs

### ISSUE THREAD

**Issue by dunghacknicktao** [student9128/flutter_float_window#3]
Hello,
Could you please help me play the .avi video in iOS device?

Best regards

**Comment by student9128** [comment]
> Hello, Could you please help me play the .avi video in iOS device?
> 
> Best regards

flutter_float_window play video in iOS with AVPlayer, unless something unexpected, it can support all the format that AVPlayer support. but i didn't test it

**Comment by dunghacknicktao** [comment]
Could you please help me get the current position a
Can you help me get the current position value after I trigger FullScreen button to enter onFullScreenClick event?
I try use FlutterFloatWindow.getDurationAndPosition() but it returned no value and caused the process to get stuck..

**Comment by student9128** [comment]
> Could you please help me get the current position a Can you help me get the current position value after I trigger FullScreen button to enter onFullScreenClick event? I try use FlutterFloatWindow.getDurationAndPosition() but it returned no value and caused the process to get stuck..

use the code like this
```
var x = await FlutterFloatWindow.getDurationAndPosition();
var position = x['position'];
var duration = x['duration'];
print("position=$position,duration=$duration");
```
i've tested, it is normal.

**Comment by student9128** [comment]
![image](https://github.com/student9128/flutter_float_window/assets/16153648/db098382-d9f2-4df0-ad21-8890aaffe16b)

this is the source code in iOS, please check is there something wrong

**Comment by dunghacknicktao** [comment]
> > Could you please help me get the current position a Can you help me get the current position value after I trigger FullScreen button to enter onFullScreenClick event? I try use FlutterFloatWindow.getDurationAndPosition() but it returned no value and caused the process to get stuck..
> 
> use the code like this
> 
> ```
> var x = await FlutterFloatWindow.getDurationAndPosition();
> var position = x['position'];
> var duration = x['duration'];
> print("position=$position,duration=$duration");
> ```
> 
> i've tested, it is normal.

My code implement for android in below:
case "onFullScreenClick":
          debugPrint('onFullScreenClick');
          FlutterFloatWindow.launchApp();
          print("----------- android: onVideoFullScreenClick");
          var x = await FlutterFloatWindow.getDurationAndPosition();
          var position = x['position'];
          var duration = x['duration'];
          print("position=$position,duration=$duration");
...

Then no result return :(( - and log:
E/com.kevin.flutterfloatwindow.flutter_float_window.FlutterFloatWindowPlugin$initFloatWindow$1(32489): onFullScreenClick Native
I/flutter (32489): onFullScreenClick
I/flutter (32489): ----------- android: onVideoFullScreenClick
D/com.kevin.flutterfloatwindow.flutter_float_window.FloatWindowService$initView$1(32489): playWhenReady====1
D/SurfaceUtils(32489): connecting to surface 0x7c0a9fc95d70, reason connectToSurface
I/MediaCodec(32489): [c2.goldfish.h264.decoder] setting surface generation to 33268753
D/SurfaceUtils(32489): disconnecting from surface 0x7c0a9fc95d70, reason connectToSurface(reconnect)
D/SurfaceUtils(32489): connecting to surface 0x7c0a9fc95d70, reason connectToSurface(reconnect)
D/Codec2-OutputBufferQueue(32489): remote graphic buffer migration 13/13
D/Codec2Client(32489): setOutputSurface -- failed to set consumer usage (6/BAD_INDEX)
D/Codec2Client(32489): setOutputSurface -- generation=33268753 consumer usage=0x900
D/Codec2Client(32489): Surface configure completed
D/SurfaceUtils(32489): disconnecting from surface 0x7c0a9fceaff0, reason disconnectFromSurface
D/EGL_emulation(32489): app_time_stats: avg=9755.51ms min=9755.51ms max=9755.51ms count=1

**Comment by student9128** [comment]
> > > Could you please help me get the current position a Can you help me get the current position value after I trigger FullScreen button to enter onFullScreenClick event? I try use FlutterFloatWindow.getDurationAndPosition() but it returned no value and caused the process to get stuck..
> > 
> > 
> > use the code like this
> > ```
> > var x = await FlutterFloatWindow.getDurationAndPosition();
> > var position = x['position'];
> > var duration = x['duration'];
> > print("position=$position,duration=$duration");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i've tested, it is normal.
> 
> My code implement for android in below: case "onFullScreenClick": debugPrint('onFullScreenClick'); FlutterFloatWindow.launchApp(); print("----------- android: onVideoFullScreenClick"); var x = await FlutterFloatWindow.getDurationAndPosition(); var position = x['position']; var duration = x['duration']; print("position=$position,duration=$duration"); ...
> 
> Then no result return :(( - and log: E/com.kevin.flutterfloatwindow.flutter_float_window.FlutterFloatWindowPlugin$initFloatWindow$1(32489): onFullScreenClick Native I/flutter (32489): onFullScreenClick I/flutter (32489): ----------- android: onVideoFullScreenClick D/com.kevin.flutterfloatwindow.flutter_float_window.FloatWindowService$initView$1(32489): playWhenReady====1 D/SurfaceUtils(32489): connecting to surface 0x7c0a9fc95d70, reason connectToSurface I/MediaCodec(32489): [c2.goldfish.h264.decoder] setting surface generation to 33268753 D/SurfaceUtils(32489): disconnecting from surface 0x7c0a9fc95d70, reason connectToSurface(reconnect) D/SurfaceUtils(32489): connecting to surface 0x7c0a9fc95d70, reason connectToSurface(reconnect) D/Codec2-OutputBufferQueue(32489): remote graphic buffer migration 13/13 D/Codec2Client(32489): setOutputSurface -- failed to set consumer usage (6/BAD_INDEX) D/Codec2Client(32489): setOutputSurface -- generation=33268753 consumer usage=0x900 D/Codec2Client(32489): Surface configure completed D/SurfaceUtils(32489): disconnecting from surface 0x7c0a9fceaff0, reason disconnectFromSurface D/EGL_emulation(32489): app_time_stats: avg=9755.51ms min=9755.51ms max=9755.51ms count=1

oh, the code can only use for iOS
if you want get position in Android, use code like this
 ```
var x = await FlutterFloatWindow.hideFloatWindow();
```
it can only get position.
